# Generated by Django 2.0.5 on 2018-06-15 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0002_auto_20180615_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('created_by', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('pay_date', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Authorized'), (3, 'Paid')])),
                ('created_by', models.PositiveIntegerField()),
                ('authorized_by', models.PositiveIntegerField(null=True)),
                ('paid_by', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayRollItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('employee_nssf_contribution', models.DecimalField(decimal_places=3, max_digits=13)),
                ('employer_nssf_contribution', models.DecimalField(decimal_places=3, max_digits=13)),
                ('nssf_amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('local_service_taxable_amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('annual_local_service_tax_paid', models.DecimalField(decimal_places=3, max_digits=13)),
                ('annual_local_service_tax_to_be_paid', models.DecimalField(decimal_places=3, max_digits=13)),
                ('net_pay', models.DecimalField(decimal_places=3, max_digits=13)),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Authorized'), (3, 'Paid')])),
                ('created_by', models.PositiveIntegerField()),
                ('deductions', models.ManyToManyField(to='payapp.Deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payapp.Employee')),
                ('pay_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payapp.PayRoll')),
            ],
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=13)),
                ('created_by', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payapp.Employee')),
                ('pay_roll_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payapp.PayRoll')),
            ],
        ),
    ]
