# Generated by Django 2.0.5 on 2018-06-17 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_deduction_payroll_payrollitem_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pay_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='start_date',
            field=models.DateField(),
        ),
    ]
