# Generated by Django 2.0.5 on 2018-06-17 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_auto_20180617_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deduction',
            name='created_by',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='authorized_by',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='paid_by',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
