# Generated by Django 2.0.5 on 2018-06-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0005_auto_20180617_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollitem',
            name='annual_local_service_tax_paid',
        ),
        migrations.AddField(
            model_name='deduction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Paid'), (2, 'Not paid')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payroll',
            name='created_by',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
