# Generated by Django 2.0.5 on 2018-07-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0007_remove_payrollitem_deductions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollitem',
            old_name='employee_nssf_contribution',
            new_name='nssf_contribution',
        ),
        migrations.RenameField(
            model_name='payrollitem',
            old_name='nssf_amount',
            new_name='pay_as_you_earn',
        ),
        migrations.RemoveField(
            model_name='payrollitem',
            name='employer_nssf_contribution',
        ),
    ]
