# Generated by Django 2.0.5 on 2018-07-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0010_auto_20180713_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollitem',
            name='status',
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not paid'), (2, 'Pending'), (3, 'Paid')]),
        ),
    ]
