# Generated by Django 2.0.5 on 2018-08-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0011_auto_20180721_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='localservicetax',
            name='payroll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payapp.PayRoll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localservicetax',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
