# Generated by Django 2.0.5 on 2018-08-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0013_auto_20180812_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='paid_by',
            new_name='approved_by',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_by',
        ),
        migrations.AddField(
            model_name='payroll',
            name='prepared_by',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
