# Generated by Django 2.0.5 on 2018-08-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0014_auto_20180812_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollitem',
            name='created_by',
        ),
    ]
