# Generated by Django 2.0.5 on 2018-08-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0015_remove_payrollitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
