# Generated by Django 2.0.5 on 2018-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0016_auto_20180812_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(default=1, max_length=20, verbose_name='NSSF Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(default=1, max_length=20, verbose_name='TIN'),
            preserve_default=False,
        ),
    ]
