# Generated by Django 2.0.5 on 2018-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0017_auto_20180812_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='local_service_tax_amount',
            field=models.DecimalField(choices=[(10000.0, 'UGX 10,000'), (20000.0, 'UGX 20,000'), (30000.0, 'UGX 30,000'), (400000.0, 'UGX 40,000'), (500000.0, 'UGX 50,000'), (600000.0, 'UGX 60,000'), (700000.0, 'UGX 70,000'), (800000.0, 'UGX 80,000'), (90000.0, 'UGX 90,000'), (100000.0, 'UGX 100,000')], decimal_places=3, max_digits=13),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TIN'),
        ),
    ]
